In [1]:
import pandas as pd

In [7]:
df.shape

(1000, 18)

In [4]:
df.head(5)

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1

In [8]:
df=df.drop_duplicates()

In [9]:
df.shape

(1000, 18)

In [10]:
df.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome'],
      dtype='object')

In [12]:
df=df.drop(columns=["Processing Time (seconds)","Accuracy Score","Missing Data Indicator","Normalized Transaction Amount"])

In [13]:
df.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Transaction Outcome'],
      dtype='object')

In [14]:
df["Operating Expenses"]

0      4098
1      3872
2      4780
3      4948
4      3289
       ...
995    2240
996    3317
997    2494
998    4277
999    1658
Name: Operating Expenses, Length: 1000, dtype: int64

In [20]:
df.convert_dtypes(convert_string="Transaction Outcome")

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1

In [21]:
for x in df.index:
    if (x,["Transaction Outcome"])==1:
        df["Transaction Outcome"].str.replace("Yes")
    else:
        df["Transaction Outcome"].str.replace("No")

AttributeError: Can only use .str accessor with string values!

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction ID        1000 non-null   int64
 1   Date                  1000 non-null   object
 2   Account Type          1000 non-null   object
 3   Transaction Amount    1000 non-null   int64
 4   Cash Flow             1000 non-null   int64
 5   Net Income            1000 non-null   int64
 6   Revenue               1000 non-null   int64
 7   Expenditure           1000 non-null   int64
 8   Profit Margin         1000 non-null   float64
 9   Debt-to-Equity Ratio  1000 non-null   float64
 10  Operating Expenses    1000 non-null   int64
 11  Gross Profit          1000 non-null   int64
 12  Transaction Volume    1000 non-null   int64
 13  Transaction Outcome   1000 non-null   int64
dtypes: float64(2), int64(10), object(2)
memory usage: 109.5+ KB

In [2]:
import pandas as pd

df=pd.read_csv(r"C:\Users\User\Downloads\accounting_data.csv")

In [4]:
df.head()

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1

In [5]:
df.tail()

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1

In [6]:
df.shape

(1000, 18)

In [7]:
df.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Transaction ID                 1000 non-null   int64
 1   Date                           1000 non-null   object
 2   Account Type                   1000 non-null   object
 3   Transaction Amount             1000 non-null   int64
 4   Cash Flow                      1000 non-null   int64
 5   Net Income                     1000 non-null   int64
 6   Revenue                        1000 non-null   int64
 7   Expenditure                    1000 non-null   int64
 8   Profit Margin                  1000 non-null   float64
 9   Debt-to-Equity Ratio           1000 non-null   float64
 10  Operating Expenses             1000 non-null   int64
 11  Gross Profit                   1000 non-null   int64
 12  Transaction Volume             1000 non-null   int64
 13  Processing Time (seconds)      1000 non-null   float64
 14  Accuracy Score                 1000 non-null   float64
 15  Missing Data Indicator         1000 non-null   bool
 16  Normalized Transaction Amount  1000 non-null   float64
 17  Transaction Outcome            1000 non-null   int64
dtypes: bool(1), float64(5), int64(10), object(2)
memory usage: 133.9+ KB

In [10]:
df.describe().corr()

,Transaction ID,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Normalized Transaction Amount,Transaction Outcome
Transaction ID,1.000000,0.651334,0.630279,0.676487,0.636208,0.693500,0.520591,0.522067,0.654277,0.690707,0.526219,0.521327,0.520420,0.520850,0.520794
Transaction Amount,0.651334,1.000000,0.994980,0.998611,0.998896,0.997929,-0.308483,-0.306833,0.999750,0.998450,-0.302187,-0.307659,-0.308664,-0.308198,-0.308253
Cash Flow,0.630279,0.994980,1.000000,0.996209,0.998464,0.992938,-0.327984,-0.326328,0.995375,0.993362,-0.321727,-0.327147,-0.328111,-0.327721,-0.327757
Net Income,0.676487,0.998611,0.996209,1.000000,0.998377,0.998751,-0.274742,-0.273065,0.998511,0.999240,-0.268369,-0.273900,-0.274902,-0.274462,-0.274500
Revenue,0.636208,0.998896,0.998464,0.998377,1.000000,0.996240,-0.325563,-0.323914,0.998801,0.996800,-0.319295,-0.324734,-0.325719,-0.325289,-0.325336
Expenditure,0.693500,0.997929,0.992938,0.998751,0.996240,1.000000,-0.253696,-0.252017,0.998507,0.999846,-0.247293,-0.252857,-0.253878,-0.253406,-0.253470
Profit Margin,0.520591,-0.308483,-0.327984,-0.274742,-0.325563,-0.253696,1.000000,0.999998,-0.304867,-0.257484,0.999978,1.000000,1.000000,1.000000,1.000000
Debt-to-Equity Ratio,0.522067,-0.306833,-0.326328,-0.273065,-0.323914,-0.252017,0.999998,1.000000,-0.303214,-0.255805,0.999988,1.000000,0.999998,0.999999,0.999999
Operating Expenses,0.654277,0.999750,0.995375,0.998511,0.998801,0.998507,-0.304867,-0.303214,1.000000,0.998720,-0.298563,-0.304042,-0.305048,-0.304582,-0.304641
Gross Profit,0.690707,0.998450,0.993362,0.999240,0.996800,0.999846,-0.257484,-0.255805,0.998720,1.000000,-0.251086,-0.256645,-0.257663,-0.257196,-0.257251
Transaction Volume,0.526219,-0.302187,-0.321727,-0.268369,-0.319295,-0.247293,0.999978,0.999988,-0.298563,-0.251086,1.000000,0.999983,0.999977,0.999980,0.999979
Processing Time (seconds),0.521327,-0.307659,-0.327147,-0.273900,-0.324734,-0.252857,1.000000,1.000000,-0.304042,-0.256645,0.999983,1.000000,0.999999,1.000000,1.000000
Accuracy Score,0.520420,-0.308664,-0.328111,-0.274902,-0.325719,-0.253878,1.000000,0.999998,-0.305048,-0.257663,0.999977,0.999999,1.000000,1.000000,1.000000
Normalized Transaction Amount,0.520850,-0.308198,-0.327721,-0.274462,-0.325289,-0.253406,1.000000,0.999999,-0.304582,-0.257196,0.999980,1.000000,1.000000,1.000000,1.000000
Transaction Outcome,0.520794,-0.308253,-0.327757,-0.274500,-0.325336,-0.253470,1.000000,0.999999,-0.304641,-0.257251,0.999979,1.000000,1.000000,1.000000,1.000000

In [11]:
df.isna().sum()

Transaction ID                   0
Date                             0
Account Type                     0
Transaction Amount               0
Cash Flow                        0
Net Income                       0
Revenue                          0
Expenditure                      0
Profit Margin                    0
Debt-to-Equity Ratio             0
Operating Expenses               0
Gross Profit                     0
Transaction Volume               0
Processing Time (seconds)        0
Accuracy Score                   0
Missing Data Indicator           0
Normalized Transaction Amount    0
Transaction Outcome              0
dtype: int64

In [12]:
df.fillna("ASad")

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1

In [13]:
df.fillna(df.median)

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1

In [14]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [15]:
df[df.duplicated()]

Empty DataFrame
Columns: [Transaction ID, Date, Account Type, Transaction Amount, Cash Flow, Net Income, Revenue, Expenditure, Profit Margin, Debt-to-Equity Ratio, Operating Expenses, Gross Profit, Transaction Volume, Processing Time (seconds), Accuracy Score, Missing Data Indicator, Normalized Transaction Amount, Transaction Outcome]
Index: []

In [16]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Transaction ID, Date, Account Type, Transaction Amount, Cash Flow, Net Income, Revenue, Expenditure, Profit Margin, Debt-to-Equity Ratio, Operating Expenses, Gross Profit, Transaction Volume, Processing Time (seconds), Accuracy Score, Missing Data Indicator, Normalized Transaction Amount, Transaction Outcome]
Index: []

In [17]:
df.drop_duplicates()

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1

In [18]:
df.interpolate()

C:\Users\User\AppData\Local\Temp\ipykernel_11224\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1

In [19]:
df.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome'],
      dtype='object')

AttributeError: 'DataFrame' object has no attribute 'group_by'