In [1]:
print("hello world")

hello world

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

In [6]:
df=pd.read_csv(r"C:\Users\User\Downloads\music_recommendations (1).csv")

In [5]:
df.head()

,track_name,artist_name,genre,similarity_score,similarity_percent
0,lately,moneybagg yo,hip hop,0.316829,31.7%
1,since i fell for you,dinah washington,blues,0.284011,28.4%
2,slowly,webb pierce,country,0.257575,25.8%
3,regret,new order,pop,0.247513,24.8%
4,from now on,supertramp,rock,0.241575,24.2%

In [6]:
df.shape

(10, 5)

In [8]:
df.shape #for understanding a shape of our dataset//

(10, 5)

In [9]:
df.head()

,track_name,artist_name,genre,similarity_score,similarity_percent
0,lately,moneybagg yo,hip hop,0.316829,31.7%
1,since i fell for you,dinah washington,blues,0.284011,28.4%
2,slowly,webb pierce,country,0.257575,25.8%
3,regret,new order,pop,0.247513,24.8%
4,from now on,supertramp,rock,0.241575,24.2%

In [10]:
df.tail()  # to see the bottom 5 rows

,track_name,artist_name,genre,similarity_score,similarity_percent
5,on and on,the score,rock,0.241313,24.1%
6,scholarships,drake,pop,0.241174,24.1%
7,right place wrong time,dr. john,blues,0.235687,23.6%
8,something got me started,simply red,pop,0.232403,23.2%
9,stay,david bowie,rock,0.229558,23.0%

In [12]:
df.columns # all columns in dataset

Index(['track_name', 'artist_name', 'genre', 'similarity_score',
       'similarity_percent'],
      dtype='object')

In [13]:
df.dtypes

track_name             object
artist_name            object
genre                  object
similarity_score      float64
similarity_percent     object
dtype: object

In [14]:
df.describe() # statistics information

       similarity_score
count         10.000000
mean           0.252764
std            0.027420
min            0.229558
25%            0.237059
50%            0.241444
75%            0.255060
max            0.316829

In [15]:
# step 1: import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use("ggplot")
import random as rd
import math as mt
# step 2: data exploaration
pd.read_csv("path")
pd.head()
pd.tail()
pd.shape
pd.columns
pd.describe()
pd.info()
pd.dtypes
# step 3:data manipulation

In [7]:
df=df.columns

In [8]:
df[['track_name', 'artist_name', 'genre', 'similarity_score',
       'similarity_percent']]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [9]:
df.drop(["columns name"],axis=1)
# this is used for dropping columns

TypeError: Index.drop() got an unexpected keyword argument 'axis'

In [10]:
df.shape

(5,)

In [13]:
df=pd.describe()

AttributeError: module 'pandas' has no attribute 'describe'

In [14]:
pd.to_numeric("convert into numeric")

ValueError: Unable to parse string "convert into numeric" at position 0

In [15]:
df.rename("renaming the columns")

Index(['track_name', 'artist_name', 'genre', 'similarity_score',
       'similarity_percent'],
      dtype='object', name='renaming the columns')

In [16]:
df.rename(columns={"oldName":"NewName"})

TypeError: Index.rename() got an unexpected keyword argument 'columns'

In [20]:
df.isna().sum() #to find missing valiues

np.int64(0)

In [23]:
data=pd.read_csv(r"C:\Users\User\OneDrive\Documents\accounting_data.csv")

In [24]:
data.head()

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1

In [25]:
data.shape

(1000, 18)

In [26]:
data.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome'],
      dtype='object')

In [27]:
data.index

RangeIndex(start=0, stop=1000, step=1)

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Transaction ID                 1000 non-null   int64
 1   Date                           1000 non-null   object
 2   Account Type                   1000 non-null   object
 3   Transaction Amount             1000 non-null   int64
 4   Cash Flow                      1000 non-null   int64
 5   Net Income                     1000 non-null   int64
 6   Revenue                        1000 non-null   int64
 7   Expenditure                    1000 non-null   int64
 8   Profit Margin                  1000 non-null   float64
 9   Debt-to-Equity Ratio           1000 non-null   float64
 10  Operating Expenses             1000 non-null   int64
 11  Gross Profit                   1000 non-null   int64
 12  Transaction Volume             1000 non-null   int64
 13  Processing Time (seconds)      1000 non-null   float64
 14  Accuracy Score                 1000 non-null   float64
 15  Missing Data Indicator         1000 non-null   bool
 16  Normalized Transaction Amount  1000 non-null   float64
 17  Transaction Outcome            1000 non-null   int64
dtypes: bool(1), float64(5), int64(10), object(2)
memory usage: 133.9+ KB

In [29]:
data.describe()

,Transaction ID,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Normalized Transaction Amount,Transaction Outcome
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,2535.701000,2426.331000,2114.759000,2610.989000,2026.188000,0.499085,1.781955,2517.95100,2039.058000,4.987000,1.235095,0.898512,0.496668,0.951000
std,288.819436,1432.052409,1169.845927,1100.614577,1358.787787,1129.047997,0.171064,0.720989,1418.44947,1128.130368,2.589118,0.437929,0.056868,0.292734,0.215976
min,1.000000,106.000000,502.000000,203.000000,303.000000,100.000000,0.201363,0.500605,103.00000,101.000000,1.000000,0.500066,0.800554,0.000000,0.000000
25%,250.750000,1363.500000,1360.750000,1168.750000,1426.000000,1004.750000,0.354579,1.157240,1290.00000,1067.000000,3.000000,0.864168,0.848545,0.257052,1.000000
50%,500.500000,2498.000000,2452.000000,2075.500000,2570.500000,2048.000000,0.492161,1.818015,2549.00000,2039.000000,5.000000,1.213391,0.897044,0.488962,1.000000
75%,750.250000,3774.000000,3414.000000,3078.500000,3776.500000,3009.500000,0.642220,2.375929,3735.50000,3007.500000,7.000000,1.623384,0.947914,0.749796,1.000000
max,1000.000000,4998.000000,4496.000000,3995.000000,4997.000000,3998.000000,0.798427,2.999644,4999.00000,3995.000000,9.000000,1.999773,0.999934,1.000000,1.000000

In [31]:
data['Transaction ID'].nunique()

1000

In [32]:
data['Transaction ID'].value_counts()

Transaction ID
1000    1
1       1
2       1
3       1
4       1
       ..
13      1
12      1
11      1
10      1
9       1
Name: count, Length: 1000, dtype: int64

In [36]:
data.nunique()

Transaction ID                   1000
Date                             1000
Account Type                        4
Transaction Amount                910
Cash Flow                         893
Net Income                        883
Revenue                           907
Expenditure                       866
Profit Margin                    1000
Debt-to-Equity Ratio             1000
Operating Expenses                914
Gross Profit                      897
Transaction Volume                  9
Processing Time (seconds)        1000
Accuracy Score                   1000
Missing Data Indicator              2
Normalized Transaction Amount     910
Transaction Outcome                 2
dtype: int64

In [38]:
data.isnull().sum()

Transaction ID                   0
Date                             0
Account Type                     0
Transaction Amount               0
Cash Flow                        0
Net Income                       0
Revenue                          0
Expenditure                      0
Profit Margin                    0
Debt-to-Equity Ratio             0
Operating Expenses               0
Gross Profit                     0
Transaction Volume               0
Processing Time (seconds)        0
Accuracy Score                   0
Missing Data Indicator           0
Normalized Transaction Amount    0
Transaction Outcome              0
dtype: int64

In [40]:
data.dropna().sum()

Transaction ID                                                              500500
Date                             2025-01-012025-01-022025-01-032025-01-042025-0...
Account Type                     AssetAssetRevenueExpenseExpenseRevenueRevenueA...
Transaction Amount                                                         2535701
Cash Flow                                                                  2426331
Net Income                                                                 2114759
Revenue                                                                    2610989
Expenditure                                                                2026188
Profit Margin                                                           499.085211
Debt-to-Equity Ratio                                                   1781.955297
Operating Expenses                                                         2517951
Gross Profit                                                               2039058
Transaction Volume                                                            4987
Processing Time (seconds)                                              1235.094956
Accuracy Score                                                          898.512222
Missing Data Indicator                                                          48
Normalized Transaction Amount                                           496.668234
Transaction Outcome                                                            951
dtype: object

In [41]:
data.fillna(0)

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1

In [42]:
data.fillna().mean()

ValueError: Must specify a fill 'value' or 'method'.

In [43]:
data.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome'],
      dtype='object')

In [46]:
data[['Transaction ID','Transaction Outcome']]

     Transaction ID  Transaction Outcome
0                 1                    1
1                 2                    1
2                 3                    1
3                 4                    1
4                 5                    1
..              ...                  ...
995             996                    0
996             997                    1
997             998                    1
998             999                    1
999            1000                    1

[1000 rows x 2 columns]

In [47]:
data.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome'],
      dtype='object')

In [48]:
data["TotalSales"]=data['Revenue']*data['Profit Margin']

In [49]:
data['TotalSales']

0      1904.851219
1      1669.224038
2      2281.282200
3       966.637078
4      2524.203864
          ...
995    2003.761557
996    1366.810422
997    1582.866295
998     957.083979
999    1849.442429
Name: TotalSales, Length: 1000, dtype: float64

In [52]:
data.rename(columns= {"TotalSales":'Total Sales'})

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome,Total Sales
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1,1904.851219
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1,1669.224038
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1,2281.282200
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1,966.637078
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1,2524.203864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0,2003.761557
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1,1366.810422
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1,1582.866295
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1,957.083979
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1,1849.442429

In [53]:
data.columns

Index(['Transaction ID', 'Date', 'Account Type', 'Transaction Amount',
       'Cash Flow', 'Net Income', 'Revenue', 'Expenditure', 'Profit Margin',
       'Debt-to-Equity Ratio', 'Operating Expenses', 'Gross Profit',
       'Transaction Volume', 'Processing Time (seconds)', 'Accuracy Score',
       'Missing Data Indicator', 'Normalized Transaction Amount',
       'Transaction Outcome', 'TotalSales'],
      dtype='object')

In [62]:
data['Revenue']>400

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Name: Revenue, Length: 1000, dtype: bool

In [63]:
data.sort_values('Revenue', ascending=False)

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome,TotalSales
111,112,2025-04-22,Asset,341,1764,3823,4997,1337,0.494298,0.794434,3588,2352,3,0.675046,0.912560,False,0.048038,1,2470.009273
901,902,2027-06-21,Asset,3389,2992,2956,4993,2106,0.471227,0.735501,497,2181,7,0.776647,0.951168,False,0.671096,1,2352.836671
227,228,2025-08-16,Liability,293,3101,1604,4987,1944,0.369070,1.657455,2497,1545,2,1.776909,0.847854,False,0.038226,1,1840.550733
693,694,2026-11-25,Revenue,2270,4422,3797,4986,867,0.736984,2.421071,1614,3931,4,1.663938,0.843339,False,0.442355,1,3674.601716
984,985,2027-09-12,Expense,2392,3826,3253,4982,2874,0.519062,2.477125,1666,3150,1,1.690796,0.874614,False,0.467294,1,2585.968149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,22,2025-01-22,Expense,1358,3832,3694,326,2370,0.515983,2.477616,3266,2250,3,0.871114,0.885215,False,0.255928,1,168.210338
403,404,2026-02-08,Expense,2703,2916,2523,322,1545,0.370415,2.783433,793,3362,6,1.241202,0.969507,False,0.530867,1,119.273622
270,271,2025-09-28,Liability,2034,2853,810,321,565,0.560997,1.594206,614,120,1,0.730543,0.978131,False,0.394113,1,180.080192
126,127,2025-05-07,Asset,3740,584,3353,308,3548,0.745327,1.549888,4635,2996,1,1.735985,0.905406,False,0.742845,1,229.560707
33,34,2025-02-03,Revenue,3879,1360,874,303,3883,0.658020,2.167068,2531,1045,4,1.007385,0.869939,False,0.771259,1,199.380118

In [64]:
data.drop_duplicates()

,Transaction ID,Date,Account Type,Transaction Amount,Cash Flow,Net Income,Revenue,Expenditure,Profit Margin,Debt-to-Equity Ratio,Operating Expenses,Gross Profit,Transaction Volume,Processing Time (seconds),Accuracy Score,Missing Data Indicator,Normalized Transaction Amount,Transaction Outcome,TotalSales
0,1,2025-01-01,Asset,1176,3184,2174,3137,1823,0.607221,2.067004,4098,2327,8,1.894686,0.959936,False,0.218724,1,1904.851219
1,2,2025-01-02,Asset,1291,3221,3236,4694,2746,0.355608,2.347537,3872,388,5,1.728990,0.966382,False,0.242232,1,1669.224038
2,3,2025-01-03,Revenue,4966,3309,3689,3363,3102,0.678347,1.901003,4780,2616,2,1.707099,0.828307,False,0.993459,1,2281.282200
3,4,2025-01-04,Expense,4641,1952,245,4373,808,0.221047,0.934125,4948,2237,8,1.750641,0.984149,False,0.927024,1,966.637078
4,5,2025-01-05,Expense,2305,2131,2037,4956,644,0.509323,1.061178,3289,1729,3,0.879708,0.929107,False,0.449509,1,2524.203864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2027-09-23,Asset,2625,2655,2152,3480,3974,0.575794,1.225116,2240,1176,6,0.571376,0.864797,False,0.514922,0,2003.761557
996,997,2027-09-24,Asset,676,1586,472,3363,1952,0.406426,1.742689,3317,1268,5,1.535432,0.985745,False,0.116517,1,1366.810422
997,998,2027-09-25,Revenue,2758,3624,2787,2702,3778,0.585813,2.290615,2494,2574,8,1.423379,0.893314,False,0.542110,1,1582.866295
998,999,2027-09-26,Liability,796,2063,3203,3855,1266,0.248271,2.229671,4277,1354,9,1.166093,0.849563,False,0.141047,1,957.083979
999,1000,2027-09-27,Expense,3387,4041,2545,4521,831,0.409078,2.353535,1658,3848,3,1.696704,0.820586,False,0.670687,1,1849.442429

In [67]:
data.groupby('Account Type')['Revenue'].mean()

Account Type
Asset        2573.631373
Expense      2696.517510
Liability    2656.956000
Revenue      2510.373950
Name: Revenue, dtype: float64

In [69]:
data.groupby('Account Type').agg(
    {
        'Revenue':'mean'
    }
)

                  Revenue
Account Type
Asset         2573.631373
Expense       2696.517510
Liability     2656.956000
Revenue       2510.373950